server:
  host: "0.0.0.0"
  port: 3272
  lang: "en-us"
  prompt: "> "
  argvSplit: " "
http:
  color: true
  inverse: false
  width: 100
  height: 40
  fontSize: 48
  size: 4
  noise: 3
  ignoreChars: "0oO1ilI"
  toLowerCase: true
  captchaHtml: "%s<br/>%s"
  captchaHeader:
    json:
      Content-Type: "text/json; charset=utf-8"
    html:
      Content-Type: "text/html; charset=utf-8"
    default:
      Content-Type: "text/json; charset=utf-8"
cmd:
  userSplit: ", "
db:
  dataFile: "data.db"
page:
  pageIdGenerator: "sha256"
  pageHeader:
    Content-Type: "text/plain; charset=utf-8"
ws:
  wsTokenGenerator: "sha256"